############开发环境配置文件###################

registry:
  url: http://${host:localhost}:808/eureka/  #注册中心的地址与端口，方便给其他微服务的配置使用

## spring配置
spring:
  datasource: #数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.116.246.59:3306/tsm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: tsm
    password: fbR8XH2ZXm6RadRK

mybatis:
  typeAliasesPackage: cn.com.heyue.model
  mapperLocations: classpath*:mapper/*.xml

#logback日志
logging:
  config: classpath:logback-spring.xml
  level:
    cn.com.heyue.mapper: debug
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    database: mysql
#    show-sql: false
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#          paths: /**
#  redis: ## Redis配置
#    host: 127.0.0.1
#    port: 6379
#    password: password
#    database: 15
#    pool:
#      max-active: 100
#      min-idle: 2
#      max-idle: 2
#      max-wait: 500

# 自定义配置
sysconfig:
  isDebug: true  #是否Debug
  swagger: true  #开启swagger

# 和包支付参数
HEBAO_PAY_URL: http://211.138.236.210/ips/cmpayService
CMPAY_MERNO: 888073117000022
CMPAY_MER_KEY: 0Joap12UKHcmwfhNdkepasRpfN2DInI6hlRUWlSQK7zhbzb1d6P3gjmhDRmoCWBR
CMPAY_NOTIFY_URL:
CMPAY_CALLBACK_URL:
HBCX_PAY_NOTIFY_URL: http://211.138.236.210/ips/cmpayService

#TSM城市服务接口地址
TSM_API_URL: http://123.150.11.50:9003/CITYPLAT
SEL_TRADEINFO_URL: ${TSM_API_URL}/selTradeInfoR
CARD_ACTIVE_URL: ${TSM_API_URL}/activeCard
CARD_ACTIVE_SUBMIT_URL: ${TSM_API_URL}/activeCommit
CARD_TRAP_URL: ${TSM_API_URL}/recharge
CARD_TRAP_SUBMIT_URL: ${TSM_API_URL}/rechargeCommit
CARD_ACCOUNT_INFO_URL: ${TSM_API_URL}/queryAccount
CARD_CONSUM_RECORD_URL: ${TSM_API_URL}/consumInfo
#发送请求私钥、公钥
TSM_LOC_PRI_KEY: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChGHmxLIf1Sv2V3EovclErn04nqMcg788ZjRZKOvpA3fPyMMyP+TB3AqK3mX84JBjGdKnt029VtjAdRMP4NJa1L/aa9BTdzq202G7vRhNXod1MU3uv5OZhX5e6Jmcyw2atIRmXPIRWjksCCJsfU9fn82JvztRt51zSh3xMElT+3Fxg5MPNBLzwTcn0s68ponl8PiEkt8YF8IvmoA4af9mSooYnhuwf9tTFv/FN6XXyKqN8IaxjHSTsXqXS//Vp9KWeBvTpZn313CwVisQEGVm9ykzyDHD179Nv/vWnF4w8x3cQoXxNzvB+XaJRE/XBwodl4nbagY/7Gk0WcTBr2qt1AgMBAAECggEBAJ3WsUUa8Isx0oyGrlkWlNk82QKap6Bp1myeg/xvFMuBrIbbsVJPQWEZv/xL9Q44r92iaOyQgUFlpHbI7Ym/XPph6CmihN9epWvPs8HU0xbFjWI/WazZhbBaTPsirXJbabqv97bqoG9+M5fmfraPG7g0C3qpGBIm4heUkACo5YZfK8f1Ji70XMQN0tkUqvrc9ZjBnECwl2tpV3wa9JgnY5knyz9kPvPyx5yTSM8X5BcPjon1eFydZNwQFlbD7Q9u/7hVdA3XdSk8Hsx3GSF/99Ulm4ESLNyGbDRHDo+w5h563jEPoq9QNAFjWDWFgF6ryE44fp9qxs+3anebJZHLCPECgYEA1oMrNusM13CCq+i2Q3cNjserUAN2VzWEBAshzwT4ejdybLDGjKOFcms6k0bD2Bu4OX5WoztpiIvDisj/Tby3efGC9QRS14dI9etiwkp66ZVyxaQg1UjRQt5zHChyGITZZq/s+rvIqwa/vfPX0K6eggWySCkbzx6bcExD55UgLmMCgYEAwECPysX0eA1Uid672H23kXVIRpqDuY79WfSl531kj4/1orFLqYcvNIYkEWyViX5Gwp6m+E56Zwc78HLgyxDolxStilncIEP9sNP4XbzmToVCpq2AQo17qVLgeE06aEltky1Akjk0ArS+sGOPJG+qZV6ncq0WDnNIfWXMh0CVWkcCgYAWHd4FwoRHbiU63jp0iEDQmMuT61d3NGBRHmi09Hk9+JuGk09VTsLCgkW+y4wDqw/6dYkvOT/vQSG/HGweMrfkDb+HzZNQ/3TJTiSXjaBQlwUHVZ3A/8n7j/3kSFNDLedQTBEt5NCSuZZpWkvFC0vyce3ovLxORYSXNnXF2b1AqwKBgQC83fAlNYmwcvANLbp+uSqghIaHjf5ASgAM4nIl06L6AmQ++0wodHzkba97SqAxXdOoGHJR188Z7hptYn4CIE9PNOoz04mUTRcqI2OIuy3KD9JlqmcpepL0yk1pAf2SPCiggMFBpV66FdSLtpMGKYlNYsq/ttjHQ2wAfQSMDt9quwKBgCC9Fe4FikasFs3JEf9gqE93CO+NuiP2AtRBCjY0G02j+6MFK5p7+LdKEU9t8L4Bxc7J2usTjWmlV7Ec8ot21SE5fjohuUt0nZRoPrX+nyCihP0BFUldCjZez9pxa/9CZZkYTYBTh+R1LA814kUJ+SQzIFVZMGtWFMf5m5ohYtxy
TSM_LOC_PUB_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoRh5sSyH9Ur9ldxKL3JRK59OJ6jHIO/PGY0WSjr6QN3z8jDMj/kwdwKit5l/OCQYxnSp7dNvVbYwHUTD+DSWtS/2mvQU3c6ttNhu70YTV6HdTFN7r+TmYV+XuiZnMsNmrSEZlzyEVo5LAgibH1PX5/Nib87Ubedc0od8TBJU/txcYOTDzQS88E3J9LOvKaJ5fD4hJLfGBfCL5qAOGn/ZkqKGJ4bsH/bUxb/xTel18iqjfCGsYx0k7F6l0v/1afSlngb06WZ99dwsFYrEBBlZvcpM8gxw9e/Tb/71pxeMPMd3EKF8Tc7wfl2iURP1wcKHZeJ22oGP+xpNFnEwa9qrdQIDAQAB;

#城市服务FTP
CITY_FTP_HOST: 123.150.11.50
CITY_FTP_PORT: 9001
CITY_FTP_USER_NAME: test
CITY_FTP_PASSWORD: test

#本地FTP
FTP_HOST: 81.69.189.227
FTP_PORT: 21
FTP_USER_NAME: tsm
FTP_PASSWORD: ~S;/mUh3Wz._j2

#制卡目录
CREATECARD_LOCAL_CATALOG: /data/tsm_cardfile/createcard_loacl_catalog/
CREATECARD_UPLOAD_CATALOG: /test/SQ/
CREATECARD_DOWNLOAD_CATALOG: /data/tsm_cardfile/createcard_download_catalog/
CREATECARD_DOWNLOAD_HISTORY: /data/tsm_cardfile/createcard_download_history_catalog/
CREATECARD_DOWNLOAD_ERROR_CATALOG: /data/tsm_cardfile/createcard_download_error_catalog/
#卡信息同步文件目录
CARDINFO_SYNFILE_LOCAL_CATALOG: /data/tsm_cardfile/cardinfo_synfile_local_catalog/
CARDINFO_SYNFILE_UPLOAD_CATALOG: /data/tsm_cardfile/cardInfo_synfile_upload_catalog/

#系统参数
VERSION: 1.0.0
TSM_ID: 686e0001
CITY_CODE: 3350
APPLY_CITY_CODE: 3140
AREA_CODE: 00
CARD_SPECIES: 1220
APP_ID: A06A78676A6B0101
MERCHANT_NO: 20200001