spring:
  profiles:
    active: ${active:dev}
  application:
    name: springCloud.zuul

server:
  port: 800
#   context-path: /zuul

#配置注册中心的参数
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:808/eureka/
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔时间 (默认为30秒)
  instance:
    lease-expiration-duration-in-seconds: 60  # 注册中心超过这个时间没收到心跳，会视为无效节点(默认为90秒)
    lease-renewal-interval-in-seconds: 30  # 发送心跳间隔时间（默认30秒）
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 50000 # 请求处理的超时时间: 默认5000ms
  ConnectTimeout: 50000 # 请求连接的超时时间: 默认50000ms
  SocketTimeout: 50000 # SocketTimeout超时时间: 默认50000ms
  MaxAutoRetries: 0 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer : 0 #切换实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 # hystrix超时时间设置 线程池隔离，默认超时时间1000ms

zuul:
  add-host-header: true #webui重定向  请求头host显示为网关的（eg:localhost:9090）而非webui的
  ignoredServices: '*' #禁用服务名路游
  sensitive-headers:   #传递头信息
  retryable: true  #负载均衡时，路游的服务重启时，可通过重试到其他相同服务
  #  host:
  #     socket-timeout-millis: 60000
  #     connect-timeout-millis: 60000
  #zuul中网路由一定要在这里配置，不然发访问不到微服务，getway不配置也可以访问
  routes:
    tsmservice:
      path: /tsm/**
      serviceId: Tsm-service