eureka:
  client:
    serviceUrl.defaultZone: http://127.0.0.1:808/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7092
spring:
  application:
    name: Tsm-service
  profiles:
    active: test